/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    copy: typeof import('./src/components/EditUser copy.vue')['default']
    CreateUser: typeof import('./src/components/CreateUser.vue')['default']
    EditUser: typeof import('./src/components/EditUser.vue')['default']
    EditUser2: typeof import('./src/components/EditUser2.vue')['default']
    EditUser3: typeof import('./src/components/EditUser3.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    ListUser: typeof import('./src/components/ListUser.vue')['default']
    ListUser3: typeof import('./src/components/ListUser3.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
